Repository 0xflotus/ip2d, pull requests merged in 2024-10, with the labels that each got.

#662 Add IPv6 Address Conversion Functions Using BigInt
  index.ts
Labels: hacktoberfest-accepted

#671 Updated the README.md file with improved documentation
  README.md
Labels: hacktoberfest-accepted

#681 Add ESLint Configuration and Update TypeScript Settings
  eslint.config.mjs
  package-lock.json
  package.json
  tsconfig.json
Labels: enhancement, hacktoberfest-accepted

#689 Add ESlint only for index.ts
  package.json
Labels: hacktoberfest-accepted, hacktoberfest

#680 Add comprehensive test cases for IPv4 and IPv6 conversions
  index.spec.ts
  index.ts
Labels: hacktoberfest-accepted, hacktoberfest

#692 fix: fix tests
  index.spec.ts
  index.ts
Labels: hacktoberfest-accepted, hacktoberfest

#695 chore: Enable linting stage in pipeline
  .github/workflows/test.yml
Labels: hacktoberfest-accepted, hacktoberfest

#698 ci: add multiple node versions for test pipelines
  .github/workflows/test.yml
Labels: hacktoberfest-accepted, hacktoberfest

#701 feat: added tests
  index.spec.ts
Labels: hacktoberfest-accepted, hacktoberfest

#711 Added Contributing.md file
  CONTRIBUTING.md
Labels: hacktoberfest-accepted, hacktoberfest
